development:
 secret_key_base: c26a31235311e569f0d2ef1d7c8ab75223a2bc4b7670707c84f12ee3e51a18f7c55616e29924433aa6fe9d65d8c5e5187b198b501a1c9170993ca61a1c17420f

test:
 secret_key_base: 0161eb6ff8202aa44890d01ed4112218afb1f995cf37859a7020e7b66b5f3529f68129307274b71329147aa168581de4a684f1f4068060374dc13995248900cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>